---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-prod
  namespace: prod
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mydb-prod"
